# ==============================================================
# Server port
# ==============================================================
server.port=8081

spring.application.name=apirental

# ==============================================================
# Configuration R2DBC (Réactif - Pour l'application)
# ==============================================================

# -----------------------------------------------------
# Config pour Neon (SSL requis)
# -----------------------------------------------------
spring.r2dbc.url=r2dbc:postgresql://ep-orange-dew-aizganm2-pooler.c-4.us-east-1.aws.neon.tech/rental_db?sslmode=require&channel_binding=require
spring.r2dbc.username=neondb_owner
spring.r2dbc.password=npg_eJbuI5oGU3zj
spring.r2dbc.properties.ssl=true


# ==============================================================
# Configuration Liquibase (JDBC - Pour la migration au démarrage)
# ==============================================================
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# ------------------------------------------------------
# config pour Neon (SSL requis)
# ------------------------------------------------------
spring.liquibase.url=jdbc:postgresql://ep-orange-dew-aizganm2-pooler.c-4.us-east-1.aws.neon.tech/rental_db?sslmode=require&channel_binding=require
spring.liquibase.user=neondb_owner
spring.liquibase.password=npg_eJbuI5oGU3zj
spring.liquibase.driver-class-name=org.postgresql.Driver


# ==============================================================
# Configuration Swagger (SpringDoc)
# ==============================================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# ==============================================================
# Configuration WebFlux
# ==============================================================
spring.webflux.base-path=/

# ==============================================================
# Configuration JWT
# ==============================================================
# Clé secrète (générez-en une forte pour la prod via la variable JWT_SECRET)
jwt.secret=${JWT_SECRET:7KyhCtwGUvIoqcxTCabQGm3FJ/F6LfCy9nmOg3hy+WA=}
jwt.expiration=86400000

# ==============================================================
# Configuration MEDIA
# ==============================================================
# Dossier où les fichiers seront stockés
application.file.upload-dir=uploads
# URL de base pour construire le lien public
# application.base-url=http://localhost:8081
application.base-url=https://apirental5gi-v2.onrender.com
